#ifndef MATRICES_H_INCLUDED
#define MATRICES_H_INCLUDED

const uint8_t pieza_I[DIMENSION_PIEZA][DIMENSION_PIEZA] = {
    {INDICE_TRANSP, INDICE_CIAN, INDICE_TRANSP, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_CIAN, INDICE_TRANSP, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_CIAN, INDICE_TRANSP, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_CIAN, INDICE_TRANSP, INDICE_TRANSP}
};

const uint8_t pieza_O[DIMENSION_PIEZA][DIMENSION_PIEZA] = {
    {INDICE_TRANSP, INDICE_AMARILLO, INDICE_AMARILLO, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_AMARILLO, INDICE_AMARILLO, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP,   INDICE_TRANSP,   INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP,   INDICE_TRANSP,   INDICE_TRANSP}
};

const uint8_t pieza_T[DIMENSION_PIEZA][DIMENSION_PIEZA] = {
    {INDICE_TRANSP, INDICE_MAGENTA, INDICE_TRANSP,  INDICE_TRANSP},
    {INDICE_MAGENTA,INDICE_MAGENTA, INDICE_MAGENTA, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP,  INDICE_TRANSP,  INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP,  INDICE_TRANSP,  INDICE_TRANSP}
};

const uint8_t pieza_S[DIMENSION_PIEZA][DIMENSION_PIEZA] = {
    {INDICE_TRANSP, INDICE_VERDE_C, INDICE_VERDE_C, INDICE_TRANSP},
    {INDICE_VERDE_C,INDICE_VERDE_C, INDICE_TRANSP,  INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP,  INDICE_TRANSP,  INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP,  INDICE_TRANSP,  INDICE_TRANSP}
};

const uint8_t pieza_Z[DIMENSION_PIEZA][DIMENSION_PIEZA] = {
    {INDICE_ROJO_C, INDICE_ROJO_C, INDICE_TRANSP, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_ROJO_C, INDICE_ROJO_C, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP, INDICE_TRANSP, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP, INDICE_TRANSP, INDICE_TRANSP}
};

const uint8_t pieza_J[DIMENSION_PIEZA][DIMENSION_PIEZA] = {
    {INDICE_AZUL_C, INDICE_TRANSP, INDICE_TRANSP, INDICE_TRANSP},
    {INDICE_AZUL_C, INDICE_AZUL_C, INDICE_AZUL_C, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP, INDICE_TRANSP, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP, INDICE_TRANSP, INDICE_TRANSP}
};

const uint8_t pieza_L[DIMENSION_PIEZA][DIMENSION_PIEZA] = {
    {INDICE_TRANSP, INDICE_TRANSP, INDICE_NARANJA, INDICE_TRANSP},
    {INDICE_NARANJA,INDICE_NARANJA,INDICE_NARANJA, INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP, INDICE_TRANSP,  INDICE_TRANSP},
    {INDICE_TRANSP, INDICE_TRANSP, INDICE_TRANSP,  INDICE_TRANSP}
};

const uint8_t textura_molde[TAM_BLOQUE][TAM_BLOQUE] =
{
    {INDICE_GRIS_CL, INDICE_GRIS_CL, INDICE_GRIS_CL, INDICE_GRIS_CL, INDICE_GRIS_CL, INDICE_GRIS_CL, INDICE_GRIS_CL,  INDICE_NEGRO},
    {INDICE_GRIS_CL, INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_GRIS_OS, INDICE_NEGRO},
    {INDICE_GRIS_CL, INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_GRIS_OS, INDICE_NEGRO},
    {INDICE_GRIS_CL, INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_GRIS_OS, INDICE_NEGRO},
    {INDICE_GRIS_CL, INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_GRIS_OS, INDICE_NEGRO},
    {INDICE_GRIS_CL, INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_RELLENO,    INDICE_GRIS_OS, INDICE_NEGRO},
    {INDICE_GRIS_CL, INDICE_GRIS_OS,INDICE_GRIS_OS,INDICE_GRIS_OS,INDICE_GRIS_OS,INDICE_GRIS_OS,INDICE_GRIS_OS, INDICE_NEGRO},
    {INDICE_NEGRO,      INDICE_NEGRO,      INDICE_NEGRO,      INDICE_NEGRO,      INDICE_NEGRO,      INDICE_NEGRO,      INDICE_NEGRO,       INDICE_NEGRO}
};

tGBT_ColorRGB paletaCGA[CANT_COLORES] =
{

    /// 0-15: Colores CGA (16 colores)
    {0x00, 0x00, 0x00}, // 0:   Negro
    {0x00, 0x00, 0xAA}, // 1:   Azul
    {0x00, 0xAA, 0x00}, // 2:   Verde
    {0x00, 0xAA, 0xAA}, // 3:   Cian
    {0xAA, 0x00, 0x00}, // 4:   Rojo
    {0xAA, 0x00, 0xAA}, // 5:   Magenta
    {0xAA, 0x55, 0x00}, // 6:   Marron
    {0xAA, 0xAA, 0xAA}, // 7:   Gris claro
    {0x55, 0x55, 0x55}, // 8:   Gris oscuro
    {0x55, 0x55, 0xFF}, // 9:   Azul brillante
    {0x55, 0xFF, 0x55}, // 10:  Verde brillante
    {0x55, 0xFF, 0xFF}, // 11:  Cian brillante
    {0xFF, 0x55, 0x55}, // 12:  Rojo brillante
    {0xFF, 0x55, 0xFF}, // 13:  Magenta brillante
    {0xFF, 0xFF, 0x55}, // 14:  Amarillo
    {0xFF, 0xFF, 0xFF}  // 15:  Usado como transparente por GBT
};

#endif // MATRICES_H_INCLUDED
